myprofile/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView

urlpatterns = patterns('myprofile.views',
    url(r'^$', RedirectView.as_view(url='/profile/view')),
    url(r'^view$', 'edit_profile', name='view_profile'),
    url(r'^view/$', 'edit_profile', name='view_profile'),
    url(r'^view/edit$', 'handle_form', name='handle_form'),
    url(r'^view/details$', 'get_details', name='get_details'),
    url(r'^view/delete$', 'delete_item', name='delete_item'),
)

qhome/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'questov1.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$','django.contrib.auth.views.login',name='login'),
    url(r'^logout/$','django.contrib.auth.views.logout',{'next_page':'/'},name='logout'),
)

questov1/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from registrations.forms import RegistrationForm
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^home/$', 'questov1.views.home', name='home'),
    #url(r'^home/$', 'questov1.views.home', name='login'),
    url(r'^contact/$', 'usermodel.views.contact', name='contact'),
    url(r'^contact-faq', 'usermodel.views.contact_faq', name='contact_faq'),
    url(r'^register/$', 'registrations.views.register', name = 'register'),
    url(r'^$','myprofile.views.home', name='home'),
    url(r'^basicinfo/$', 'myprofile.views.basicinfo', name='basicinfo'),
    url(r'^experience/$', 'myprofile.views.experience', name='experience'),
    url(r'^education/$', 'myprofile.views.education', name='education'),
    url(r'^social/$', 'myprofile.views.social', name='social'),
    url(r'^skill/$', 'myprofile.views.skill', name='skill'),
    url(r'^register/$', 'registrations.views.register', name='register'),
    url(r'^register/profile/view/edit/$', RedirectView.as_view(url='/profile/view/edit?module=Basicinfo&id=new')),
    url(r'^activate/$', 'registrations.views.activate', name='activate'),
    # url(r'^login/$', 'mysignon.views.sso_authorize', name='sso_authorize'),
    url(r'^login/$','django.contrib.auth.views.login',{'extra_context':{'signupform':RegistrationForm}},name='login'),
    # url(r'^login/$','questov1.views.login',name='login'),
    url(r'^logout/$','django.contrib.auth.views.logout',{'next_page':'/'},name='logout'),


    # url(r'^talent/', include('mydashboard.urls')),
    url(r'^talent/all/$','myprofile.views.all_talent',name='all_talent'),
    url(r'^talent/(?P<slug>[\w-]+)/$','myprofile.views.view_talent',name='talent'),
    url(r'^profile/', include('myprofile.urls')),
    url(r'^saved-search/', include('mysearches.urls')),
    # url(r'^api/', include(v1_api.urls)),
    url(r'^authorize/', include('mysignon.urls')),
    # url(r'^message/', include('mymessages.urls')),
    # url(r'^prm/', include('mypartners.urls')),
    # url(r'^posting/', include('postajob.urls')),
    url(r'^reports/', include('myreports.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myprofile/models.py
import datetime
import uuid

from django.core.validators import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save, post_delete
from django.utils.translation import ugettext_lazy as _
from collections import OrderedDict
from itertools import chain
from usermodel.models import User
# Create your models here.

class ProfileUnits(models.Model):
    """
    This is the parent class for all user information. Creating any new
    profile unit instances (Education, Name, Email etc) end up in the
    ProfileUnits queryset as well.
    
    """
    date_created = models.DateTimeField(editable=False, auto_now=False, auto_now_add= True)
    date_updated = models.DateTimeField(editable=False, auto_now=True, auto_now_add= False)
    content_type = models.ForeignKey(ContentType, editable=False, null=True)
    user = models.ForeignKey(User, editable=False, null=True, blank=True)

    def save(self, *args, **kwargs):
        """
        Custom save method to set the content type of the instance.
        
        """
        if not self.content_type:
            self.content_type = ContentType.objects.get_for_model(self.__class__)
        super(ProfileUnits, self).save(*args, **kwargs)

    def get_fields(self):
        """
        Returns the module type, value, and field type for all        
        fields on a specific model
        """
        field_list = []
        for field in self._meta.local_fields:
            if not field.primary_key:
                field_list.append([field.verbose_name.title(),
                                   self.__getattribute__(field.name),
                                   field.get_internal_type()])
        return field_list

    def __unicode__(self):
        return self.content_type

    def get_model_name(self):
        return self.content_type.model

    @classmethod
    def get_verbose_class(object):
        return object.__name__

    def get_verbose(self):
        return self.content_type.name.title()

def get_next_or_prev(models,item,direction):
    getit=False
    if direction == "prev":
        models =list(reversed(models))
    for m in models:
        if getit:
            return m
        if str(item)==str(m):
            getit=True
    if getit:
        return models[0]
    return False

Salary_Choices = (
        ('a',''),
        ('b','0-1 lakhs'),
        ('c','1-2 lakhs'),
        ('d','2-3 lakhs'),
        ('e','3-5 lakhs'),
        ('f','5-8 lakhs'),
        ('g','8-12 lakhs'),
        ('h','12-16 lakhs'),
        ('i','16-20 lakhs'),
        ('j','20+ lakhs'),
)

Job_ssChoices = (
    ('a','Actively searching'),
    ('b','Open to offers'),
    ('c','Just networking'),
)


class Basicinfo(ProfileUnits):
    name = models.CharField(max_length = 30, default = 'Name')
    mobile = models.CharField(max_length=10)
    slug = models.SlugField(unique=True)
    located_at = models.CharField(max_length=20, verbose_name = 'Current Location',null=True, blank=True)
    dateofbirth = models.DateField('Date of Birth', blank=True, auto_now=False, auto_now_add = False, null= True )
    profesional_Headline = models.CharField(max_length = 120,blank = True, null=True)
    about_you = models.TextField(null=True, blank=True)
    Job_Search_Status = models.CharField(max_length = 1, choices = Job_ssChoices, default='b' )
    desired_Salary = models.CharField(max_length = 3, choices=Salary_Choices, default=' ' )
    Website_URL = models.CharField(max_length=100, null=True, blank=True)
    Personal_URL = models.CharField(max_length=100, blank = True, null=True)
    Profile_Pic = models.FileField(upload_to = 'talent/profile_pic', blank = True, null=True)
    # employee_Referal = models.TextField(max_length = 200,blank = True, null=True )
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)

    def __unicode__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = "%s-%s"%(slugify(self.name),uuid.uuid4())
        super(Basicinfo,self).save(*args,**kwargs)

class Experience(ProfileUnits):
    title = models.CharField(max_length = 50, default = 'Title')
    company_name = models.CharField(verbose_name="Company Name", max_length = 50, default = '')
    start_date = models.DateField(verbose_name="Start Date")
    stillworking =  models.BooleanField(default=True, verbose_name=_("I still work here"))
    end_date = models.DateField(verbose_name="End Date", blank = True, null =True)
    #industries = models.CharField(max_length = 50)
    usedskills = models.CharField('Your 3 most used skills in this job', max_length = 120, null = True, blank=True)
    salary = models.CharField(max_length = 1, choices = Salary_Choices, default='a' )
    summary = models.TextField(blank = True,null= True)

    def __unicode__(self):
        return self.title

rating_choices = (
    ('',''),
    ('0','1'),
    ('1','2'),
    ('2','3'),
    ('3','4'),
    ('4','5'),
    ('5','6'),
    ('6','7'),
    ('7','8'),
    ('8','9'),
    ('9','10'),
    )

class Skill(ProfileUnits):
    skillname = models.CharField(verbose_name = "Add Your Skill", max_length=30)
    rating = models.CharField(max_length=1,choices = rating_choices, default = '')
    def __unicode__(self):
        return self.skillname

edulevel_choices = (
    ('', _('Education Level')),
    ('a', _('High School')),
    ('b', _('Non-Degree Education')),
    ('c', _('Associate')),
    ('d', _('Bachelor')),
    ('e', _('Master')),
    ('f', _('B.Tech+M.Tech')),
    ('g', _('Doctoral')),

)

class Education(ProfileUnits):
    collegename = models.CharField(verbose_name="School/College Name", max_length = 100)
    city_name = models.CharField(max_length=255, blank=True, verbose_name=_('city'))
    # country_sub_division_code = models.CharField(max_length=5, blank=True, verbose_name=_("State/Region"))
    course = models.CharField(max_length = 50)
    start_date = models.DateField(verbose_name="Start Date",blank=False)
    end_date = models.DateField(verbose_name="End Date", null=True, blank=True)
    degree = models.CharField(max_length = 1, choices = edulevel_choices, blank=True )
    activities = models.TextField(blank = True, null=True)

    def __unicode__(self):
        return self.collegename


socialchoices = (
    ('',''),
    ('f','Facebook'),
    ('t','Twitter'),
    ('l','Linkedin'),
    ('p','Google Plus'),
    ('g','Github'),
    )

class Social(ProfileUnits):
    social_select = models.CharField(max_length=1, choices=socialchoices, null=True, blank=True)
    link = models.CharField(max_length=30, null=True, blank=True)

    def __unicode__(self):
        return "%s %s"%(self.social_select,self.link)


class BaseProfileUnitManager(object):
    """
    Class for managing how profile units are displayed

    Visible units are returned by displayed_units

    Displayed and excluded models are defined as lists of model names

    Child classes can define custom display logic per model in
    <model_name>_is_displayed methods
        i.e.
            def name_is_displayed(self, unit):
                return unit.is_primary()

    Each input accepts a list of model names as strings i.e. ['name','address']
    Inputs:
    :displayed: List of units one wants to be displayed
    :excluded:  List of units one would want to exclude from being displayed
    :order:     List of units to order the output for displayed_units
    """
    def __init__(self, displayed=None, excluded=None, order=None):
        self.displayed = displayed or []
        self.excluded = excluded or []
        self.order = order or []

    def is_displayed(self, unit):
        """
        Returns True if a unit should be displayed
        Input:
        :unit: An instance of ProfileUnit
        """
        try:
            field_is_displayed = getattr(self.unit.get_model_name()+'_is_displayed')
            if field_is_displayed:
                return field_is_displayed(unit)
        except AttributeError:
            pass
        if not self.displayed and not self.excluded:
            return True
        elif self.displayed and self.excluded:
            return unit.get_model_name() in self.displayed \
                and unit.get_model_name() not in self.excluded
        elif self.excluded:
            return unit.get_model_name() not in self.excluded
        elif self.displayed:
            return unit.get_model_name() in self.displayed
        else:
            return True

    def order_units(self, profileunits, order):
        """
        Sorts the dictionary from displayed_units

        Inputs:
        :profileunits:  Dict of profileunits made in displayed_units
        :order:         List of model names (as strings)

        Outputs:
        Returns an OrderedDict of the sorted list
        """
        sorted_units = []
        units_map = {item[0]: item for item in profileunits.items()}
        for item in order:
            try:
                sorted_units.append(units_map[item])
                units_map.pop(item)
            except KeyError:
                pass
        sorted_units.extend(units_map.values())
        return OrderedDict(sorted_units)

    def displayed_units(self, profileunits):
        """
        Returns a dictionary of {model_names:[profile units]} to be displayed

         Inputs:
        :profileunits:  The default value is .all() profileunits, but you can
                        input your own QuerySet of profileunits if you are
                        using specific filters

        Outputs:
        :models:        Returns a dictionary of profileunits, an example:
                        {u'name': [<Name: Foo Bar>, <Name: Bar Foo>]}
        """
        models = {}

        for unit in profileunits:
            if self.is_displayed(unit):
                models.setdefault(unit.get_model_name(), []).append(

myprofile/forms.py
from django.conf import settings
from django.forms import *
from django.utils.translation import ugettext_lazy as _
from questov1.forms import BaseUserForm
from .models import *

def generate_custom_widgets(model):
    """
    Generates custom widgets and sets placeholder values and class names based
    on field type

    Inputs:
    :model:       model class from form Meta
    
    Outputs:
    :widgets:     dictionary of widgets with custom attributes defined
    """
    fields = model._meta.fields
    widgets = {}
    
    for field in fields:
        internal_type = field.get_internal_type()
        # exclude profile unit base fields
        if field.model == model:
            attrs = {}
            attrs['id'] = 'id_' + model.__name__.lower() + '-' + field.attname
            attrs['placeholder'] = field.verbose_name.title()
            if field.choices:
                widgets[field.attname] = Select(attrs=attrs)
            elif internal_type == 'BooleanField':
                attrs['label_class'] = 'checkbox'
                widgets[field.attname] = CheckboxInput(attrs=attrs)
            elif internal_type == 'DateField':
                widgets[field.attname] = DateInput(
                format=settings.FORM_DATE_FORMAT, attrs=attrs)
            elif internal_type == 'FileField':
                widgets[field.attname] = FileInput(attrs=attrs)
            elif internal_type == 'TextField':
                widgets[field.attname] = Textarea(attrs=attrs)
            else:
                widgets[field.attname] = TextInput(attrs=attrs)
                pass
    return widgets


class BasicinfoForm(BaseUserForm):
    class Meta:
        form_name = _("Basic Information")
        model = Basicinfo
        exclude = ['slug']
        widgets = generate_custom_widgets(model)
        
class ExperienceForm(BaseUserForm):
    def __init__(self, *args, **kwargs):
        super(ExperienceForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].input_formats = settings.DATE_INPUT_FORMATS
        self.fields['end_date'].input_formats = settings.DATE_INPUT_FORMATS

    class Meta:
        model = Experience
        widgets = generate_custom_widgets(model)
        widgets['start_date'].attrs['placeholder'] = 'ie 05/30/2005'
        widgets['end_date'].attrs['placeholder'] = 'ie 06/01/2007'
        fields = '__all__'


class EducationForm(BaseUserForm):
    def __init__(self, *args, **kwargs):
        super(EducationForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].input_formats = settings.DATE_INPUT_FORMATS
        self.fields['end_date'].input_formats = settings.DATE_INPUT_FORMATS

    class Meta:
        model = Education
        widgets = generate_custom_widgets(model)
        widgets['start_date'].attrs['placeholder'] = 'ie 05/30/2005'
        widgets['end_date'].attrs['placeholder'] = 'ie 06/01/2007'
        fields = '__all__'

class SkillForm(BaseUserForm):
    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
    
    class Meta:
        model = Skill
        fields = '__all__'
        widgets = generate_custom_widgets(model)
        

class SocialForm(BaseUserForm):
    def __init__(self, *args, **kwargs):
        super(SocialForm, self).__init__(*args, **kwargs)   
 
    class Meta:
        model = Social
        widgets = generate_custom_widgets(model)
        fields = '__all__'

templates/myprofile/edit_profile.html
{% extends "base.html" %}
{% load i18n %}
{% load model_fields %}

{% block content %}
<div class="wrapper">
    <div class="sidebar sidebar-left">
        <i class="fa fa-left"/>
    </div>
    <div class="row Talent Details">

        {% for module in profile_config.values %}
       
            {% with module.0|custom_template as c_template %}
                {% include "myprofile/profile_section.html" with the_user=the_user user=user can_edit=can_edit %}
            {% endwith  %}
        {% endfor %}
    </div>
    
        

    {% if user.is_authenticated %}
        {% if can_edit %}
            <div class="formBox right-side-fixed" id="moduleBank">
                
                <!table class="table table-bordered tables-striped">
                <div class="col-sm-4">
                    <h3>Add a New Section</h3>
                {% for module in unit_names %}
                <a class="" id="{{module}}-new-section" href="{% url 'handle_form' %}?module={{module}}&id=new">
                <button type="button" class="btn btn-default btn-block">
                    {{ module }}
                </button> 
                </a> 
                {% endfor %}
            </div>
                <!/table>
            </div>{# /moduleBank #}
        {% else %}
            <a class"" href="{% url 'talent' 'prev' %}?user={{ the_user }}">Previous</a>
            <a class"" href="{% url 'talent' 'next' %}?user={{ the_user }}">Next</a>
        {% endif %}{% endif %}
</div>{# /wrapper #}

{% endblock %}

templates/myprofile/profile_details.html
{% extends 'base.html' %}
{% load i18n %}
{% load model_fields %}

{% block content %}
<div class="row">
    <div class="span12">
        <h1>{{module.verbose}} <small>Details</small></h1>
    </div>
</div>
<div class="row">
    <div class="span8 offset2">
        <div class="formBox">
            <table class="table table-bordered table-striped">
                {% with module.item|process_field_types as fields %}
                    {% for label, value, type in fields %}
                        {% if value == None or value == "" %}
                        {% else %}
                        <tr class="row">
                            <td class="span3">{{ label }}</td>
                            {% if 'Job Search Status' in label %}
                                 <td class="span9">{{ module.item.get_Job_Search_Status_display }}</td>
                            {% elif 'Desired Salary' in label %}
                                 <td class="span9">{{ module.item.get_desired_Salary_display }}</td>
                            {% elif 'Social Select' in label %}
                                 <td class="span9">{{ module.item.get_social_select_display }}</td>
                            {% elif 'Degree' in label %}
                                 <td class="span9">{{ module.item.get_degree_display }}</td>  

                            {% else %}
                                <td class="span9">{{ value }}</td> 
                            {% endif %}
                        </tr>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </table>
            <div class="actions">
                <a class="btn primary pull-right" href="{% url 'view_profile' %}">{% trans 'Back' %}</a>
                <a class="btn pull-right" href="{% url 'handle_form' %}?id={{ module.item.id }}&module={{ module.item.get_verbose.title }}">
                    {% trans 'Edit' %}
                </a>
                <div class="clear"></div>
            </div>
        </div>{# /formBox #}
    </div>{# /span8 #}
</div>{# /row #}
{% endblock %}

templates/myprofile/profile_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block content %}
<div class="row">
    <div class="span12">
        <h1>
            {% if item_id == "new" %}

            {% trans 'Add' %}

            {% else %}

            {% trans 'Edit' %}

            {% endif %}

            <small>{% trans verbose %}</small>
        </h1>
    </div>
</div>

<div class="row">
    <div class="span10 offset1">
        <form action="" method="post" id="profile-unit-form" enctype="multipart/form-data"> {% csrf_token %}
            {% for field in form %} 
                <div class="row" id="{{ module }}-{{ field.name }}">          
                    <div class="col-sm-4">
                        {{ field.label|safe }}
                    </div>          
                    <div class="col-sm-8">
                        {{ field }}
                        {% for error in field.errors %}
                            <!div class="alert alert-error">
                            <div class="control-group {%if field.errors %}error{% endif %}">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    </div>
                    <br/><hr/>
                </div>
            {% endfor %}
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <!div class="alert alert-error">
                    <div class="control-group {%if field.errors %}error{% endif %}">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            <div class="actions">
                <div class="form-label pull-left">&nbsp;</div>
                {% if item_id != "new" and module != "Basicinfo"  %}
                    <a button id="delete"  class="btn" href="{% url 'delete_item' %}?item={{ item_id }}">{% trans 'Delete' %}</a>
                {% endif %}

                <a href="{% url 'view_profile' %}" class="btn">{% trans 'Cancel' %}</a>
                <button type="submit" class="btn primary" id="profile-save">{% trans 'Save' %}</button>
            </div>{# /actions #}
        </form>
    </div>{# /span10 #}
</div>{# /row #}

<head>
    <link href="{% static 'calendar/jquery-ui.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'calendar/jquery-1.10.2.js' %}"></script> 
    <script type="text/javascript" src="{% static 'calendar/jquery-ui.js' %}"></script> 
    
<script>
    $(document).ready(function() { 
        $("#random").datepicker();
        $("#id_experience-start_date").datepicker({
          changeMonth: true,
          changeYear: true
        });
        $("#id_experience-end_date").datepicker({
          changeMonth: true,
          changeYear: true
        });
        $("#id_education-start_date").datepicker({
          changeMonth: true,
          changeYear: true
        });
        $("#id_education-end_date").datepicker({
          changeMonth: true,
          changeYear: true
        });
        $("#id_basicinfo-dateofbirth").datepicker({
          changeMonth: true,
          changeYear: true
        });
    }); 
</script> 
</head> 
<script>
//     document.getElementById("id_experience-end_date").required = true;
//     document.getElementById("id_experience-start_date").datepicker();
//     $('#id_experience-stillworking').change(function(){
//             if(this.checked){
//                 $('#Experience-end_date').hide()
//                 document.getElementById("id_experience-end_date").required = false;
//             }
//             else{
//                 $('#Experience-end_date').show()
//                 $('#Experience-end_date').datepicker();
//                 document.getElementById("id_experience-end_date").required = true;
//             }
//         });
// </script>

  <script>
  $(function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#id_skill-skillname" ).autocomplete({
      source: availableTags,
      autoFocus: true,
    });
  });
  </script>

  <script>
  $(function() {
    var availableTags = [
      "Delhi",
      "Mumbai",
      "Rajasthan",
      "Punjab",
      "Banglore",
      "Pune",
      "Hyderabad",
      "Kolkata",
      "Patana",
      "Ranchi",
      "Dhanbad",
    ];
    $( "#id_basicinfo-located_at" ).autocomplete({
      source: availableTags,
      autoFocus: true,
    });
  });
  </script>
{% endblock %}

templates/myprofile/profile_section.html
{% load i18n %}
    {% if "social" in module.0.get_model_name %}
        <div class="col-sm-4" align="left" style="border-style:dotted; border-width:thin;">
            {% for item in module %}
                <a href="https://{{ item.get_social_select_display|lower }}.com/{{ item.link }}" target="_blank"><i class="fa fa-{{ item.get_social_select_display|lower }} fa-2x"></i></a>{% if can_edit %}<a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}"><span class="glyphicon glyphicon-pencil"></span></a>{% endif %}&nbsp&nbsp
            {% endfor %}
        </div>

    {% elif "skill" in module.0.get_model_name %}
        <div class="col-sm-12" style="border-style:dotted; border-width:thin; margin-top:20px; margin-bottom:20px">
            <p style="margin-top:20px"> Skrillex </p>
            {% for item in module %}
                <div class="col-sm-3" style="right-margin:20px">{% if can_edit %}<a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}"><span class="glyphicon glyphicon-pencil"></span></a>{% endif %}
                    <div class="progress">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow={{ item.get_rating_display }} aria-valuemin="0" aria-valuemax="10" style="width: {{ item.get_rating_display }}0%;min-width:1%">
                            {{ item.skillname }} : {{ item.get_rating_display }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    {% elif "experience" in module.0.get_model_name %}
        <div class="col-sm-12"  style="border-style:dotted; border-width:thin;">
            <div class="panel-group" id="accordion"><h3>Work Experience</h3>
                {% for item in module|dictsort:"end_date" reversed %}
                    <div class="panel panel-info">
                        <div class="panel-heading" id="accordion">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ item.id }}" style="margin:0px">
                                    <h4 style="margin:0px">
                                        <p>{{ item.title }} <small> {{ item.start_date }} - {% if item.stillworking %}Present{% else %}{{ item.end_date }}{% endif %}  ({{ item.start_date|timesince:item.end_date }}) {% if user.is_authenticated %}{% if can_edit %}<a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}"><span class="glyphicon glyphicon-pencil"></span></a>
                                        {% endif %}{% endif %}</small></p>
                                        <p>{{ item.company_name }}</p>
                                        <p><small>Skills Used: {{ item.usedskills }}</small><p>


                                    </h4>
                                </a>
                            </h4>
                        </div>

                        <div id="collapse{{ item.id }}" class="panel-collapse collapse"  align="left">
                            <div class="panel-body">
                                    {{ item.summary }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% elif "education" in module.0.get_model_name %}
        <div class="col-sm-12"  style="border-style:dotted; border-width:thin;">
            <div class="panel-group" id="accordion"><h3>Education Details</h3>
                {% for item in module|dictsort:"start_date" reversed %}
                    <div class="panel panel-info">
                        <div class="panel-heading" id="accordion">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ item.id }}" style="margin:0px">
                                    <h4 style="margin:0px">
                                        <p>{{ item.get_degree_display }} in {{ item.course }}
                                        {% if user.is_authenticated %}{% if can_edit %}<a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}"><span class="glyphicon glyphicon-pencil"></span></a></p>
                                        {% endif %}{% endif %}</small></p>
                                        <p>{{ item.collegename }}<small> {{ item.city_name }} ({{ item.start_date }} - {% if not item.end_date %}Present{% else %}{{ item.end_date }}{% endif %})</small><p>
                                    </h4>
                                </a>
                            </h4>
                        </div>

                        <div id="collapse{{ item.id }}" class="panel-collapse collapse"  align="left">
                            <div class="panel-body" style="max-height:200px">
                                    {{ item.activities }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% else %}
        {% if c_template %}
        {{ c_template }}
            {% include c_template with the_user=the_user can_edit=can_edit %}
        
        {% endif %}
    {% endif %}